# 自动化部署到测试机
name: dev Docker

on:
  push:
    branches: [master]
    paths:
      - 'src/**'
      - '.github/workflows/**'
      - 'docker-compose.yml'
      - 'Dockerfile'
  pull_request:
    branches: [master]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # git pll 拉取最新代码
      - name: set ssh key
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.ID_RSA}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 8.136.209.34 >> ~/.ssh/known_hosts
      - name: deploy # 部署
        run: |
          ssh root@8.136.209.34 "
            cd /opt/blogs;
            mkdir editor-server;
            git init;
            git config --global --unset http.proxy;
            git config --global --unset https.proxy;
            git remote add origin https://${{secrets.TFW_TOKEN}}@github.com/JokerTar/JokerTar.github.io.git;
            git pull origin deploy;
            git remote remove origin;
            # 启动 docker
            # docker-compose build editor-server;
            # docker-compose up -d;
          "
      - name: delete ssh key
        run: |
          rm -rf ~/.ssh/id_rsa
