# 自动化部署到测试机
name: dev Docker

on:
  push:
    branches: [master]
    paths:
      - 'src/**'
      - '.github/workflows/**'
      - 'docker-compose.yml'
      - 'Dockerfile'
  pull_request:
    branches: [master]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # git pll 拉取最新代码
      - name: install node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14.x'
      - name: install deps
        run: npm install
      - name: build app
        run: npm run build
      - name: copy dist file with scp
        uses: appleboy/scp-action@v0.0.1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASS }}
          port: 22
          source: 'docs/.vuepress/dist'
          target: '/opt/blogs/dist'
